const KEY_DESCRIPTIONS: { [key: string]: string } = {
  Key: 'Description',
  KC_NO: 'Ignore this key (NOOP)',
  KC_TRANSPARENT: 'Use the next lowest non-transparent key',
  KC_A: 'a and A',
  KC_B: 'b and B',
  KC_C: 'c and C',
  KC_D: 'd and D',
  KC_E: 'e and E',
  KC_F: 'f and F',
  KC_G: 'g and G',
  KC_H: 'h and H',
  KC_I: 'i and I',
  KC_J: 'j and J',
  KC_K: 'k and K',
  KC_L: 'l and L',
  KC_M: 'm and M',
  KC_N: 'n and N',
  KC_O: 'o and O',
  KC_P: 'p and P',
  KC_Q: 'q and Q',
  KC_R: 'r and R',
  KC_S: 's and S',
  KC_T: 't and T',
  KC_U: 'u and U',
  KC_V: 'v and V',
  KC_W: 'w and W',
  KC_X: 'x and X',
  KC_Y: 'y and Y',
  KC_Z: 'z and Z',
  KC_1: '1 and !',
  KC_2: '2 and @',
  KC_3: '3 and #',
  KC_4: '4 and $',
  KC_5: '5 and %',
  KC_6: '6 and ^',
  KC_7: '7 and &',
  KC_8: '8 and *',
  KC_9: '9 and (',
  KC_0: '0 and )',
  KC_ENTER: 'Return (Enter)',
  KC_ESCAPE: 'Escape',
  KC_BSPACE: 'Delete (Backspace)',
  KC_TAB: 'Tab',
  KC_SPACE: 'Spacebar',
  KC_MINUS: '- and _',
  KC_EQUAL: '= and +',
  KC_LBRACKET: '[ and {',
  KC_RBRACKET: '] and }',
  KC_BSLASH: '\\ and \\|',
  KC_NONUS_HASH: 'Non-US # and ~',
  KC_SCOLON: '; and :',
  KC_QUOTE: '\' and "',
  KC_GRAVE: '` and ~, JIS Zenkaku/Hankaku',
  KC_COMMA: ', and <',
  KC_DOT: '. and >',
  KC_SLASH: '/ and ?',
  KC_CAPSLOCK: 'Caps Lock',
  KC_F1: 'F1',
  KC_F2: 'F2',
  KC_F3: 'F3',
  KC_F4: 'F4',
  KC_F5: 'F5',
  KC_F6: 'F6',
  KC_F7: 'F7',
  KC_F8: 'F8',
  KC_F9: 'F9',
  KC_F10: 'F10',
  KC_F11: 'F11',
  KC_F12: 'F12',
  KC_PSCREEN: 'Print Screen',
  KC_SCROLLLOCK: 'Scroll Lock, Brightness Down (macOS)',
  KC_PAUSE: 'Pause, Brightness Up (macOS)',
  KC_INSERT: 'Insert',
  KC_HOME: 'Home',
  KC_PGUP: 'Page Up',
  KC_DELETE: 'Forward Delete',
  KC_END: 'End',
  KC_PGDOWN: 'Page Down',
  KC_RIGHT: 'Right Arrow',
  KC_LEFT: 'Left Arrow',
  KC_DOWN: 'Down Arrow',
  KC_UP: 'Up Arrow',
  KC_NUMLOCK: 'Keypad Num Lock and Clear',
  KC_KP_SLASH: 'Keypad /',
  KC_KP_ASTERISK: 'Keypad *',
  KC_KP_MINUS: 'Keypad -',
  KC_KP_PLUS: 'Keypad +',
  KC_KP_ENTER: 'Keypad Enter',
  KC_KP_1: 'Keypad 1 and End',
  KC_KP_2: 'Keypad 2 and Down Arrow',
  KC_KP_3: 'Keypad 3 and Page Down',
  KC_KP_4: 'Keypad 4 and Left Arrow',
  KC_KP_5: 'Keypad 5',
  KC_KP_6: 'Keypad 6 and Right Arrow',
  KC_KP_7: 'Keypad 7 and Home',
  KC_KP_8: 'Keypad 8 and Up Arrow',
  KC_KP_9: 'Keypad 9 and Page Up',
  KC_KP_0: 'Keypad 0 and Insert',
  KC_KP_DOT: 'Keypad . and Delete',
  KC_NONUS_BSLASH: 'Non-US \\ and \\|',
  KC_APPLICATION: 'Application (Windows Context Menu Key)',
  KC_POWER: 'System Power',
  KC_KP_EQUAL: 'Keypad =',
  KC_F13: 'F13',
  KC_F14: 'F14',
  KC_F15: 'F15',
  KC_F16: 'F16',
  KC_F17: 'F17',
  KC_F18: 'F18',
  KC_F19: 'F19',
  KC_F20: 'F20',
  KC_F21: 'F21',
  KC_F22: 'F22',
  KC_F23: 'F23',
  KC_F24: 'F24',
  KC_EXECUTE: 'Execute',
  KC_HELP: 'Help',
  KC_MENU: 'Menu',
  KC_SELECT: 'Select',
  KC_STOP: 'Stop',
  KC_AGAIN: 'Again',
  KC_UNDO: 'Undo',
  KC_CUT: 'Cut',
  KC_COPY: 'Copy',
  KC_PASTE: 'Paste',
  KC_FIND: 'Find',
  KC__MUTE: 'Mute',
  KC__VOLUP: 'Volume Up',
  KC__VOLDOWN: 'Volume Down',
  KC_LOCKING_CAPS: 'Locking Caps Lock',
  KC_LOCKING_NUM: 'Locking Num Lock',
  KC_LOCKING_SCROLL: 'Locking Scroll Lock',
  KC_KP_COMMA: 'Keypad ,',
  KC_KP_EQUAL_AS400: 'Keypad = on AS/400 keyboards',
  KC_INT1: 'JIS \\ and _',
  KC_INT2: 'JIS Katakana/Hiragana',
  KC_INT3: 'JIS ¥ and \\|',
  KC_INT4: 'JIS Henkan',
  KC_INT5: 'JIS Muhenkan',
  KC_INT6: 'JIS Numpad ,',
  KC_INT7: 'International 7',
  KC_INT8: 'International 8',
  KC_INT9: 'International 9',
  KC_LANG1: 'Hangul/English',
  KC_LANG2: 'Hanja',
  KC_LANG3: 'JIS Katakana',
  KC_LANG4: 'JIS Hiragana',
  KC_LANG5: 'JIS Zenkaku/Hankaku',
  KC_LANG6: 'Language 6',
  KC_LANG7: 'Language 7',
  KC_LANG8: 'Language 8',
  KC_LANG9: 'Language 9',
  KC_ALT_ERASE: 'Alternate Erase',
  KC_SYSREQ: 'SysReq/Attention',
  KC_CANCEL: 'Cancel',
  KC_CLEAR: 'Clear',
  KC_PRIOR: 'Prior',
  KC_RETURN: 'Return',
  KC_SEPARATOR: 'Separator',
  KC_OUT: 'Out',
  KC_OPER: 'Oper',
  KC_CLEAR_AGAIN: 'Clear/Again',
  KC_CRSEL: 'CrSel/Props',
  KC_EXSEL: 'ExSel',
  KC_LCTRL: 'Left Control',
  KC_LSHIFT: 'Left Shift',
  KC_LALT: 'Left Alt (Option)',
  KC_LGUI: 'Left GUI (Windows/Command/Meta key)',
  KC_RCTRL: 'Right Control',
  KC_RSHIFT: 'Right Shift',
  KC_RALT: 'Right Alt (Option/AltGr)',
  KC_RGUI: 'Right GUI (Windows/Command/Meta key)',
  KC_SYSTEM_POWER: 'System Power Down',
  KC_SYSTEM_SLEEP: 'System Sleep',
  KC_SYSTEM_WAKE: 'System Wake',
  KC_AUDIO_MUTE: 'Mute',
  KC_AUDIO_VOL_UP: 'Volume Up',
  KC_AUDIO_VOL_DOWN: 'Volume Down',
  KC_MEDIA_NEXT_TRACK: 'Next Track',
  KC_MEDIA_PREV_TRACK: 'Previous Track',
  KC_MEDIA_STOP: 'Stop Track',
  KC_MEDIA_PLAY_PAUSE: 'Play/Pause Track',
  KC_MEDIA_SELECT: 'Launch Media Player',
  KC_MEDIA_EJECT: 'Eject',
  KC_MAIL: 'Launch Mail',
  KC_CALCULATOR: 'Launch Calculator',
  KC_MY_COMPUTER: 'Launch My Computer',
  KC_WWW_SEARCH: 'Browser Search',
  KC_WWW_HOME: 'Browser Home',
  KC_WWW_BACK: 'Browser Back',
  KC_WWW_FORWARD: 'Browser Forward',
  KC_WWW_STOP: 'Browser Stop',
  KC_WWW_REFRESH: 'Browser Refresh',
  KC_WWW_FAVORITES: 'Browser Favorites',
  KC_MEDIA_FAST_FORWARD: 'Next Track',
  KC_MEDIA_REWIND: 'Previous Track',
  KC_BRIGHTNESS_UP: 'Brightness Up',
  KC_BRIGHTNESS_DOWN: 'Brightness Down',
  RESET: 'Put the keyboard into bootloader mode for flashing',
  DEBUG: 'Toggle debug mode',
  EEPROM_RESET: "Reinitializes the keyboard's EEPROM (persistent memory)",
  AU_ON: 'Turns on Audio Feature',
  AU_OFF: 'Turns off Audio Feature',
  AU_TOG: 'Toggles Audio state',
  CLICKY_TOGGLE: 'Toggles Audio clicky mode',
  CLICKY_UP: 'Increases frequency of the clicks',
  CLICKY_DOWN: 'Decreases frequency of the clicks',
  CLICKY_RESET: 'Resets frequency to default',
  MU_ON: 'Turns on Music Mode',
  MU_OFF: 'Turns off Music Mode',
  MU_TOG: 'Toggles Music Mode',
  MU_MOD: 'Cycles through the music modes',
  BL_TOGG: 'Turn the backlight on or off',
  BL_STEP: 'Cycle through backlight levels',
  BL_ON: 'Set the backlight to max brightness',
  BL_OFF: 'Turn the backlight off',
  BL_INC: 'Increase the backlight level',
  BL_DEC: 'Decrease the backlight level',
  BL_BRTG: 'Toggle backlight breathing',
  MAGIC_SWAP_CONTROL_CAPSLOCK: 'Swap Caps Lock and Left Control',
  MAGIC_UNSWAP_CONTROL_CAPSLOCK: 'Unswap Caps Lock and Left Control',
  MAGIC_CAPSLOCK_TO_CONTROL: 'Treat Caps Lock as Control',
  MAGIC_UNCAPSLOCK_TO_CONTROL: 'Stop treating Caps Lock as Control',
  MAGIC_SWAP_LCTL_LGUI: 'Swap Left Control and GUI',
  MAGIC_UNSWAP_LCTL_LGUI: 'Unswap Left Control and GUI',
  MAGIC_SWAP_RCTL_RGUI: 'Swap Right Control and GUI',
  MAGIC_UNSWAP_RCTL_RGUI: 'Unswap Right Control and GUI',
  MAGIC_SWAP_CTL_GUI: 'Swap Control and GUI on both sides',
  MAGIC_UNSWAP_CTL_GUI: 'Unswap Control and GUI on both sides',
  MAGIC_TOGGLE_CTL_GUI: 'Toggle Control and GUI swap on both sides',
  MAGIC_SWAP_LALT_LGUI: 'Swap Left Alt and GUI',
  MAGIC_UNSWAP_LALT_LGUI: 'Unswap Left Alt and GUI',
  MAGIC_SWAP_RALT_RGUI: 'Swap Right Alt and GUI',
  MAGIC_UNSWAP_RALT_RGUI: 'Unswap Right Alt and GUI',
  MAGIC_SWAP_ALT_GUI: 'Swap Alt and GUI on both sides',
  MAGIC_UNSWAP_ALT_GUI: 'Unswap Alt and GUI on both sides',
  MAGIC_TOGGLE_ALT_GUI: 'Toggle Alt and GUI swap on both sides',
  MAGIC_NO_GUI: 'Disable the GUI keys',
  MAGIC_UNNO_GUI: 'Enable the GUI keys',
  MAGIC_SWAP_GRAVE_ESC: 'Swap ` and Escape',
  MAGIC_UNSWAP_GRAVE_ESC: 'Unswap ` and Escape',
  MAGIC_SWAP_BACKSLASH_BACKSPACE: 'Swap \\ and Backspace',
  MAGIC_UNSWAP_BACKSLASH_BACKSPACE: 'Unswap \\ and Backspace',
  MAGIC_HOST_NKRO: 'Enable N-key rollover',
  MAGIC_UNHOST_NKRO: 'Disable N-key rollover',
  MAGIC_TOGGLE_NKRO: 'Toggle N-key rollover',
  MAGIC_EE_HANDS_LEFT:
    'Set the master half of a split keyboard as the left hand (for EE_HANDS)',
  MAGIC_EE_HANDS_RIGHT:
    'Set the master half of a split keyboard as the right hand (for EE_HANDS)',
  OUT_AUTO: 'Automatically switch between USB and Bluetooth',
  OUT_USB: 'USB only',
  OUT_BT: 'Bluetooth only',
  DYN_REC_START1: 'Start recording Macro 1',
  DYN_REC_START2: 'Start recording Macro 2',
  DYN_MACRO_PLAY1: 'Replay Macro 1',
  DYN_MACRO_PLAY2: 'Replay Macro 2',
  DYN_REC_STOP: 'Finish the macro that is currently being recorded.',
  GRAVE_ESC: 'Escape when pressed, ` when Shift or GUI are held',
  KC_LOCK: 'Hold down the next key pressed, until the key is pressed again',
  'DF(layer)': 'Set the base (default) layer',
  'MO(layer)':
    'Momentarily turn on layer when pressed (requires KC_TRNS on destination layer)',
  'OSL(layer)': 'Switch to layer for one keypress',
  'LM(layer, mod)':
    'Momentarily turn on layer (like MO) with mod active as well.  Where mod is a mods_bit.  Mods can be viewed ',
  'LT(layer, kc)': 'Turn on layer when held, kc when tapped',
  'TG(layer)': 'Toggle layer on or off',
  'TO(layer)':
    'Turns on layer and turns off all other layers, except the default layer',
  'TT(layer)':
    "Normally acts like MO unless it's tapped multiple times, which toggles layer on",
  KC_LEAD: 'Begins a leader sequence',
  KC_MS_UP: 'Mouse Cursor Up',
  KC_MS_DOWN: 'Mouse Cursor Down',
  KC_MS_LEFT: 'Mouse Cursor Left',
  KC_MS_RIGHT: 'Mouse Cursor Right',
  KC_MS_BTN1: 'Mouse Button 1',
  KC_MS_BTN2: 'Mouse Button 2',
  KC_MS_BTN3: 'Mouse Button 3',
  KC_MS_BTN4: 'Mouse Button 4',
  KC_MS_BTN5: 'Mouse Button 5',
  KC_MS_WH_UP: 'Mouse Wheel Up',
  KC_MS_WH_DOWN: 'Mouse Wheel Down',
  KC_MS_WH_LEFT: 'Mouse Wheel Left',
  KC_MS_WH_RIGHT: 'Mouse Wheel Right',
  KC_MS_ACCEL0: 'Set mouse acceleration to 0',
  KC_MS_ACCEL1: 'Set mouse acceleration to 1',
  KC_MS_ACCEL2: 'Set mouse acceleration to 2',
  'LCTL(kc)': 'Hold Left Control and press kc',
  'LSFT(kc)': 'Hold Left Shift and press kc',
  'LALT(kc)': 'Hold Left Alt and press kc',
  'LGUI(kc)': 'Hold Left GUI and press kc',
  'RCTL(kc)': 'Hold Right Control and press kc',
  'RSFT(kc)': 'Hold Right Shift and press kc',
  'RALT(kc)': 'Hold Right Alt (AltGr) and press kc',
  'RGUI(kc)': 'Hold Right GUI and press kc',
  'SGUI(kc)': 'Hold Left Shift and GUI and press kc',
  'LCA(kc)': 'Hold Left Control and Alt and press kc',
  'LSA(kc)': 'Hold Left Shift and Left Alt and press kc',
  'RSA(kc)': 'Hold Right Shift and Right Alt (AltGr) and press kc',
  'RCS(kc)': 'Hold Right Control and Right Shift and press kc',
  'LCAG(kc)': 'Hold Left Control, Alt and GUI and press kc',
  'MEH(kc)': 'Hold Left Control, Shift and Alt and press kc',
  'HYPR(kc)': 'Hold Left Control, Shift, Alt and GUI and press kc',
  KC_MEH: 'Left Control, Shift and Alt',
  KC_HYPR: 'Left Control, Shift, Alt and GUI',
  'MT(mod, kc)': 'mod when held, kc when tapped',
  'LCTL_T(kc)': 'Left Control when held, kc when tapped',
  'LSFT_T(kc)': 'Left Shift when held, kc when tapped',
  'LALT_T(kc)': 'Left Alt when held, kc when tapped',
  'LGUI_T(kc)': 'Left GUI when held, kc when tapped',
  'RCTL_T(kc)': 'Right Control when held, kc when tapped',
  'RSFT_T(kc)': 'Right Shift when held, kc when tapped',
  'RALT_T(kc)': 'Right Alt (AltGr) when held, kc when tapped',
  'RGUI_T(kc)': 'Right GUI when held, kc when tapped',
  'SGUI_T(kc)': 'Left Shift and GUI when held, kc when tapped',
  'LCA_T(kc)': 'Left Control and Alt when held, kc when tapped',
  'LSA_T(kc)': 'Left Shift and Left Alt when held, kc when tapped',
  'RSA_T(kc)': 'Right Shift and Right Alt (AltGr) when held, kc when tapped',
  'RCS_T(kc)': 'Right Control and Right Shift when held, kc when tapped',
  'LCAG_T(kc)': 'Left Control, Alt and GUI when held, kc when tapped',
  'RCAG_T(kc)': 'Right Control, Alt and GUI when held, kc when tapped',
  'C_S_T(kc)': 'Left Control and Shift when held, kc when tapped',
  'MEH_T(kc)': 'Left Control, Shift and Alt when held, kc when tapped',
  'HYPR_T(kc)':
    'Left Control, Shift, Alt and GUI when held, kc when tapped - more info ',
  RGB_TOG: 'Toggle RGB lighting on or off',
  RGB_MODE_FORWARD: 'Cycle through modes, reverse direction when Shift is held',
  RGB_MODE_REVERSE:
    'Cycle through modes in reverse, forward direction when Shift is held',
  RGB_HUI: 'Increase hue, decrease hue when Shift is held',
  RGB_HUD: 'Decrease hue, increase hue when Shift is held',
  RGB_SAI: 'Increase saturation, decrease saturation when Shift is held',
  RGB_SAD: 'Decrease saturation, increase saturation when Shift is held',
  RGB_VAI: 'Increase value (brightness), decrease value when Shift is held',
  RGB_VAD: 'Decrease value (brightness), increase value when Shift is held',
  RGB_MODE_PLAIN: 'Static (no animation) mode',
  RGB_MODE_BREATHE: 'Breathing animation mode',
  RGB_MODE_RAINBOW: 'Rainbow animation mode',
  RGB_MODE_SWIRL: 'Swirl animation mode',
  RGB_MODE_SNAKE: 'Snake animation mode',
  RGB_MODE_KNIGHT: '"Knight Rider" animation mode',
  RGB_MODE_XMAS: 'Christmas animation mode',
  RGB_MODE_GRADIENT: 'Static gradient animation mode',
  RGB_MODE_RGBTEST: 'Red,Green,Blue test animation mode',
  RGB_SPI:
    'Increase effect speed (does not support eeprom yet), decrease speed when Shift is held',
  RGB_SPD:
    'Decrease effect speed (does not support eeprom yet), increase speed when Shift is held',
  PRINT_ON: 'Start printing everything the user types',
  PRINT_OFF: 'Stop printing everything the user types',
  KC_TILDE: '~',
  KC_EXCLAIM: '!',
  KC_AT: '@',
  KC_HASH: '#',
  KC_DOLLAR: '$',
  KC_PERCENT: '%',
  KC_CIRCUMFLEX: '^',
  KC_AMPERSAND: '&',
  KC_ASTERISK: '*',
  KC_LEFT_PAREN: '(',
  KC_RIGHT_PAREN: ')',
  KC_UNDERSCORE: '_',
  KC_PLUS: '+',
  KC_LEFT_CURLY_BRACE: '{',
  KC_RIGHT_CURLY_BRACE: '}',
  KC_PIPE: '\\|',
  KC_COLON: ':',
  KC_DOUBLE_QUOTE: '"',
  KC_LEFT_ANGLE_BRACKET: '<',
  KC_RIGHT_ANGLE_BRACKET: '>',
  KC_QUESTION: '?',
  'OSM(mod)': 'Hold mod for one keypress',
  KC_LCPO: 'Left Control when held, ( when tapped',
  KC_RCPC: 'Right Control when held, ) when tapped',
  KC_LSPO: 'Left Shift when held, ( when tapped',
  KC_RSPC: 'Right Shift when held, ) when tapped',
  KC_LAPO: 'Left Alt when held, ( when tapped',
  KC_RAPC: 'Right Alt when held, ) when tapped',
  KC_SFTENT: 'Right Shift when held, Enter when tapped',
  'SH_T(key)': 'Sends key with a tap; momentary swap when held.',
  SW_ON: 'Turns on swapping and leaves it on.',
  SW_OFF:
    'Turn off swapping and leaves it off. Good for returning to a known state.',
  SH_MON:
    'Swaps hands when pressed, returns to normal when released (momentary).',
  SH_MOFF: 'Momentarily turns off swap.',
  SH_TG: 'Toggles swap on and off with every key press.',
  SH_TT: 'Toggles with a tap; momentary when held.',
  SH_OS: 'One shot swap hands: toggle while pressed or until next key press.',
  'UC(c)': 'Send Unicode code point c',
  'X(i)': 'Send Unicode code point at index i in unicode_map',
  'XP(i, j)': 'Send Unicode code point at index i, or j if Shift/Caps is on',
  UNICODE_MODE_FORWARD: 'Cycle through selected input modes',
  UNICODE_MODE_REVERSE: 'Cycle through selected input modes in reverse',
  UNICODE_MODE_MAC: 'Switch to macOS input',
  UNICODE_MODE_LNX: 'Switch to Linux input',
  UNICODE_MODE_WIN: 'Switch to Windows input',
  UNICODE_MODE_BSD: 'Switch to BSD input (not implemented)',
  UNICODE_MODE_WINC: 'Switch to Windows input using WinCompose',
};

export default KEY_DESCRIPTIONS;
